// <auto-generated />
namespace MusixService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Patch06 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Patch06));
        
        string IMigrationMetadata.Id
        {
            get { return "201609041749026_Patch06"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
